### ISSUE TITLE
GaussianCopula.Random returns samples uniformly distributed

### ISSUE THREAD

**Issue by dmey** [DanielBok/copulae#13]
I noticed that when invoking the random method, samples are returned following a uniform distribution. Is this meant to be the case -- why is `random` not mapping the samples back to the original marginal distributions? 
 
``` python
from copulae.datasets import load_residuals
from copulae import GaussianCopula

residuals = load_residuals()

n_samples, ndim = residuals.shape
g_cop = GaussianCopula(dim=ndim)
g_cop.fit(residuals)

fig, ax = plt.subplots(1,2)
rv = g_cop.random(n_samples)
ax[0].hist(residuals.values[:, 1])
ax[0].set_title('Residuals')
ax[1].hist(rv[:,1])
ax[1].set_title('Generated')
plt.plot()
```

![image](https://user-images.githubusercontent.com/26348635/68532813-d7ee3600-0319-11ea-84ae-6e70ce9d5f79.png)

**Comment by DanielBok** [comment]
Yup, it's meant to be the case. Assuming **H** is the function you are studying

![Sklar](https://user-images.githubusercontent.com/9165086/68536885-08bf8100-0395-11ea-8d56-c9bd692db22c.png)

Then by [Sklar's Theorem](https://en.wikipedia.org/wiki/Copula_(probability_theory)#Sklar's_theorem), it can also be expressed as a copula, **C**, with univariate margins, **F**. 

Since the copula does not store the function that generated each univariate margin, you have to apply the inverse transformation to recover the original marginals. In most cases, it's a simple call to the quantile function (or distribution.ppf(x)).

**Comment by dmey** [comment]
Thanks -- I was a bit confused by the fact this is not implicitly done by `GaussianCopula.Random`. So if I understand this correctly in `copulae` you always assume this to be a post-processing step that is carried out by the user?

**Comment by DanielBok** [comment]
Yup. A short example to clarify

```python
import numpy as np
from scipy.stats import norm, expon

u = np.random.uniform(size=(100, 2))   # assume this to be generated from the copula

# assume these are you marginal distributions
d1 =norm(0.5, 2)
d2 = expon(1)

# then your marginals
m1 = d1.ppf(u[:, 0])
m2 = d2.ppf(u[:, 1])
```
