### ISSUE TITLE
Requirement to Fit Input Data

### ISSUE THREAD

**Issue by njalex22** [DanielBok/copulae#38]
Hello, based on my understanding of copulas and experience using them in other languages, I believe the input data must be uniformly distributed before it can be fit to a copula. This is specified in definition 1, point 2 [here](http://www.columbia.edu/~mh2078/QRM/Copulas.pdf). This is appears to be consistent with your example, where you fit a gaussian copula to data and state that the function will internally convert the data to psuedo observations [here](https://copulae.readthedocs.io/en/latest/examples/usage_guide.html). I have a few questions:

1. What exact method is being used to conduct the probability integral transform to convert the data to pseudo observations and where can I find this in your code? I assume you are using the emprical CDF, but I wanted to be sure.
2. If I choose another distribution for the probability integral transform and the input data is already uniformly distributed, will the function further modify the input data in any way?
3. You appear to still be checking that the input data is uniformly distributed [here](https://github.com/DanielBok/copulae/blob/2a312c2b849f95cfb2b40b381d34bc790d9d80c5/copulae/copula/estimator/estimator.py#L76). Does this check occur after the internal conversion to pseudo observations?

Thank you!

**Comment by DanielBok** [comment]
Hello,

1. To the first question, we use ranking. The basic idea is to order the data from 1...N and then divide by N. See the code snippets
    - [pseudo_obs](https://github.com/DanielBok/copulae/blob/master/copulae/core/misc.py#L37)
    - [rank_data](https://github.com/DanielBok/copulae/blob/master/copulae/core/misc.py#L37)
2. If I understand this question correctly, it wouldn't. Assume you had a data that you drew from some distribution and you did the integral transform (convert it to between 0 and 1), then it's result should be the same.
    - You can try the following (pseudo-code here!:
       1. Generate some random variables. `norm.random(n=100)`
       2. Get the cdf (integral transform) of it `norm.cdf(rvs)`
       3. `assert cdf == psuedo_obs(rvs)`
3. Not all copula classes converts the inputs to pseudo-obs. I believe empirical copulas don't. See [Issue 21](https://github.com/DanielBok/copulae/issues/21). The other copulae should convert data to pseudo-obs when they receive it because it generally doesn't hurt (from experience, most researchers forget to pass in the integral transform as inputs and just put in the raw data) and doesn't cost too much computation (done only once).
    - The general principle is that I try my best to choose sane defaults and abstract certain data transformations so researchers can have less stuff to consider in their head. It's possible to tweak any settings you'd like. 

Hope this addresses your questions

**Comment by njalex22** [comment]
Yes, that is helpful thanks! I may have another question or two as I continue to test this package, but this leaves me in a good spot right now.
